### ISSUE TITLE
Can I preserve SIMD registers using `-c reserved_regs`?

### ISSUE THREAD

**Issue by aqjune-aws** [slothy-optimizer/slothy#49]
I wonder whether it is possible to use `-c reserved_regs=[..]` to avoid assignment to v8-v15 registers.
Only low-half parts of these registers are mandatory to be preserved by the callee, but totally avoiding usage of v8-v15 is still fine in my case because my input programs use few SIMD registers.

Used script:
```
OUTPUTS="[hint_buffer0]"
RESERVED_REGS="[x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,sp,q8,q9,q10,q11,q12,q13,q14,q15,v8,v9,v10,v11,v12,v13,v14,v15]"

${SLOTHY_DIR}/slothy-cli Arm_AArch64 Arm_Neoverse_N1_experimental \
       a.s \
    -o a_opt.s \
    -c outputs=$OUTPUTS -c reserved_regs=$RESERVED_REGS \
    $REDIRECT_OUTPUT
```

Input:
```
ldr q27, [x1]                    // @slothy:reads=buffer0
umull v8.2D, v27.2S, v27.2S
mov x6, v8.d[0]
mov x12, v8.d[1]
stp x6, x12, [x1]                    // @slothy:writes=buffer0
```

The output program still contains usage of v8:
```
ldr q5, [x1]                   //(omitting the plots here)
umull v8.2D, v5.2S, v5.2S << v8 is used
...
```

I tweaked SLOTHY a bit to print all input logs to info, and I could see this diagnostic message which does exclude v8-v15:
```
INFO:slothy-cli.split.0_68:Registers available for renaming
INFO:slothy-cli.split.0_68:- GPR available: ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14',
'x15', 'x16', 'x17']
INFO:slothy-cli.split.0_68:- NEON available: ['v0', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v16', 'v17', 'v18', 'v19', 'v20', 'v21', 'v22
', 'v23', 'v24', 'v25', 'v26', 'v27', 'v28', 'v29', 'v30', 'v31']        <----- This correctly excludes v8 ~ v15..! 
```
... which might hint that it is somewhere in its downstream that omits the renaming constraint.

**Comment by hanno-becker** [comment]
@aqjune-aws Thanks! This is interesting.

Reserved registers have two properties: (1) SLOTHY will not consider introducing them for register renaming, but: (2) SLOTHY will also not change them if they are already in use.

Property (2) alone is what SLOTHY calls "locked registers" (which can be configured independently), so: Reserved registers are always locked.

Your input snippet does already use `v8`, so it being reserved->locked, SLOTHY will not change this. If you were using a different register to begin with, you should not see `v8` being introduced.

It's arguable whether reserved registers should be locked by default. However, it would be easy to add a configuration option to not mark them as locked, forcing you to also specify `-c locked_registers` if you want that behaviour.

You can quick-check that this is the issue by making the following change in `config.py`:
```python
    @property
    def locked_registers(self):
        """List of architectural registers that should not be renamed when they are
           used as output registers. Reserved registers are always treated as locked."""
        #return set(self.reserved_regs).union(self._locked_registers)
        return set(self._locked_registers)
```

Rerunning your example will eliminate `v8`.

**Comment by hanno-becker** [comment]
@aqjune-aws Please see #50. If you now add `-c /reserved_regs_are_locked` to your command line, things will work as anticipated.

**Comment by hanno-becker** [comment]
NB: You can confirm that register locking is the reason for the lack of renaming in your original example, by turning on debug logging. Unfortunately, this is still far too verbose, but if you dig a little, you'll find the following
```
DEBUG:slothy-cli.slothy.input:Instruction umull v8.2D, v27.2S, v27.2S has its output locked
DEBUG:slothy-cli.slothy.input:Reason: Register is locked
DEBUG:slothy-cli.slothy.input:Registers available for renaming of [umull v8.2D, v27.2S, v27.2S].v8 (1)
DEBUG:slothy-cli.slothy.input:['v8']
```

**Comment by aqjune-aws** [comment]
Thanks for a quick answer and the proposed patch!
Probably what I can do on my side in parallel is to avoid introduction of `v8` in the generation of input program itself.
Hope that the PR gets finally merged :)

**Comment by hanno-becker** [comment]
It's merged.
